## Metadata

title: "TODO: Add site title"
description: "TODO: Add site description"
author: "TODO: Add site author"

url: ""

## Build settings

liquid:
  error_mode: strict

## Defaults

defaults:
  - scope:
      path: ""
    values:
      layout: default
